insert into brand (name)
values ('Adagio'),
       ('Advanced Graphics'),
       ('AeroLatte'),
       ('AeroPress'),
       ('Afina'),
       ('Agraria'),
       ('Air Wick'),
       ('Alessi'),
       ('Alexander Kalifano'),
       ('Alexandria'),
       ('All American'),
       ('All-Clad'),
       ('Allstate Floral'),
       ('Alpine'),
       ('American Mills'),
       ('American Weigh'),
       ('AMIA'),
       ('Anchor Hocking'),
       ('Andrea by Sadek'),
       ('Anne Geddes'),
       ('Anolon'),
       ('Anthropologie'),
       ('Antica Farmacista'),
       ('Applica'),
       ('Aquiesse'),
       ('Archipelago Botanicals'),
       ('Aroma'),
       ('Aromatique'),
       ('Ashleigh & Burwood'),
       ('Ashton Sutton'),
       ('Aura Cacia'),
       ('Authentic Models'),
       ('Auto Expressions'),
       ('Avon'),
       ('Back to Basics'),
       ('Badash'),
       ('Ball'),
       ('Baratza'),
       ('Bard''s Bath & Body Works'),
       ('Bayou Classic'),
       ('Beanpod Candles'),
       ('Bella Cucina'),
       ('Belleek'),
       ('Betty Crocker'),
       ('Bey Berk'),
       ('Bialetti'),
       ('Biedermann & Sons'),
       ('Black & Decker'),
       ('Blendtec'),
       ('Bloomfield'),
       ('Blossom Bucket'),
       ('Blunt Power'),
       ('Bodum'),
       ('BonJour'),
       ('Bosch'),
       ('Braun'),
       ('Breadman'),
       ('Brentwood'),
       ('Breville'),
       ('Brewster Home Fashions'),
       ('Brita'),
       ('Brookstone'),
       ('Brunschwig & Fils'),
       ('Bulova'),
       ('BUNN'),
       ('Calphalon'),
       ('Calvin Klein'),
       ('Candle-Lite'),
       ('Cannon'),
       ('Capresso'),
       ('Carson Home Accents'),
       ('Casio'),
       ('CBK'),
       ('Champion'),
       ('Chantal'),
       ('Char-Broil'),
       ('Chef''s Choice'),
       ('Chef''s Secret'),
       ('CiCi Art Factory'),
       ('Circulon'),
       ('Citrus Magic'),
       ('Claire Burke'),
       ('Coaster'),
       ('Coleman'),
       ('Collector''s Gallery'),
       ('Colonial Candle'),
       ('Colonial Mills'),
       ('Conair'),
       ('Cooks Essentials'),
       ('Cooper Classics'),
       ('Copco'),
       ('Corelle'),
       ('CorningWare'),
       ('Cornwall'),
       ('Crabtree & Evelyn'),
       ('Crofton'),
       ('Cuckoo'),
       ('Cuisinart'),
       ('Cuisinox'),
       ('Cuisipro'),
       ('Dale Tiffany'),
       ('Danielson Designs'),
       ('Dansk'),
       ('DanyaB'),
       ('Darshan'),
       ('DayNa Decker'),
       ('Dazey'),
       ('DecoLav'),
       ('Deco Mesh'),
       ('DeLonghi'),
       ('Deltana'),
       ('Demdaco'),
       ('Deni'),
       ('Designers Guild'),
       ('Design Toscano'),
       ('Disney'),
       ('Donvier'),
       ('Doughmakers'),
       ('Dualit'),
       ('Ed Hardy'),
       ('Edward Meyer'),
       ('Elegant Expressions'),
       ('Elements'),
       ('Elite'),
       ('Emerson'),
       ('Emson'),
       ('Escali'),
       ('Escential Essences'),
       ('Espressione'),
       ('eSpring'),
       ('Ethan Allen'),
       ('Euro Cuisine'),
       ('Euro-Pro'),
       ('Excalibur'),
       ('Fabulous Frannie'),
       ('Fagor'),
       ('Farberware'),
       ('Fascinations'),
       ('Fathead'),
       ('Febreze'),
       ('Fetco'),
       ('Flavia'),
       ('Floracraft'),
       ('Fontanini'),
       ('Framed Art by Tilliams'),
       ('Frette'),
       ('Frieling'),
       ('Frigidaire'),
       ('Gaggia'),
       ('Ganz'),
       ('GE'),
       ('George Foreman'),
       ('Gevalia'),
       ('Giftcraft'),
       ('Glade'),
       ('Global'),
       ('Godinger'),
       ('Gonesh'),
       ('Good Cook'),
       ('Gorham'),
       ('Grasslands Road'),
       ('Greenleaf'),
       ('Green Star'),
       ('Haier'),
       ('Hallmark'),
       ('Hamilton Beach'),
       ('Hamilton Electronics'),
       ('Handpresso'),
       ('Hario'),
       ('Hearthside Collection'),
       ('Hello Kitty'),
       ('Hem'),
       ('Henckels'),
       ('HERMES'),
       ('Hilason'),
       ('Hitachi'),
       ('Hobart'),
       ('HoMedics'),
       ('Home Interiors'),
       ('Hoosier'),
       ('Howard Elliott'),
       ('Howard Miller'),
       ('Hunter'),
       ('Hurom'),
       ('Igloo'),
       ('IKEA'),
       ('Illuminations'),
       ('IMAX'),
       ('Infinity Instruments'),
       ('InterDesign'),
       ('Ives'),
       ('Jack LaLanne'),
       ('Jay Strongwater'),
       ('JCPenney'),
       ('Jenn-Air'),
       ('Jim Shore'),
       ('Joan Baker Designs'),
       ('John Deere'),
       ('Jonathan Adler'),
       ('Joyce Chen'),
       ('Joy Mangano'),
       ('Juiceman'),
       ('Juicy Couture'),
       ('Jura'),
       ('Jura-Capresso'),
       ('Kalorik'),
       ('Karlsson'),
       ('Kassel'),
       ('Kate Spade'),
       ('Kenmore'),
       ('Keurig'),
       ('Kichler'),
       ('Kikkerland'),
       ('KitchenAid'),
       ('K & K Interiors'),
       ('Koolatron'),
       ('Krups'),
       ('Kyocera'),
       ('LaCuisine'),
       ('Lama Kasso'),
       ('Lampe Berger'),
       ('Langley'),
       ('La Pavoni'),
       ('La Tee Da'),
       ('Laura Ashley'),
       ('Lavazza'),
       ('Lawrence Frames'),
       ('Le Creuset'),
       ('LEM'),
       ('Lenox'),
       ('Libbey'),
       ('Lilly Pulitzer'),
       ('Little Trees'),
       ('Lladro'),
       ('Lodge'),
       ('Longaberger'),
       ('Lumisource'),
       ('Lysol'),
       ('Magic Bullet'),
       ('Magic Chef'),
       ('Marcato'),
       ('Margaritaville'),
       ('Marimekko'),
       ('Martha Stewart'),
       ('Masterbuilt'),
       ('Mauviel'),
       ('Maxam'),
       ('Maxim'),
       ('MCS'),
       ('Medelco'),
       ('Melannco'),
       ('Melitta'),
       ('Method'),
       ('Metrokane'),
       ('Michael Aram'),
       ('Miele'),
       ('Mikasa'),
       ('Mirro'),
       ('Missoni'),
       ('Mova'),
       ('Movado'),
       ('Mr. Coffee'),
       ('Mr. Tea'),
       ('Nambe'),
       ('Nautica'),
       ('Nearly Natural'),
       ('Neonetics'),
       ('Nescafe'),
       ('Nespresso'),
       ('Nest'),
       ('New Haven'),
       ('New Leaf'),
       ('Ninja'),
       ('Nippon Kodo'),
       ('Norpro'),
       ('Nostalgia Electrics'),
       ('Nuova Simonelli'),
       ('NuTone'),
       ('Oleg Cassini'),
       ('Olivia Riegel'),
       ('Omega'),
       ('Oneida'),
       ('Oracal'),
       ('Oster'),
       ('OXO'),
       ('Ozium'),
       ('Pampered Chef'),
       ('Panasonic'),
       ('Paragon'),
       ('Park Designs'),
       ('PartyLite'),
       ('Pasta Express'),
       ('Patch Magic'),
       ('Paula Deen'),
       ('Pendleton'),
       ('Pfaltzgraff'),
       ('Philips'),
       ('Pier One'),
       ('Pillsbury'),
       ('Polder'),
       ('Pottery Barn'),
       ('Pottery Barn Kids'),
       ('Powell'),
       ('Precious Moments'),
       ('Presto'),
       ('Primula'),
       ('Prinz'),
       ('Privilege'),
       ('Proctor Silex'),
       ('Progressive International'),
       ('Punch Studio'),
       ('PUR'),
       ('Pyrex'),
       ('Quartet'),
       ('Quoizel'),
       ('Rachael Ray'),
       ('Ralph Lauren'),
       ('Rancilio'),
       ('RAZ Imports'),
       ('Regal'),
       ('Renuzit'),
       ('Replogle'),
       ('Reston Lloyd'),
       ('Restoration Hardware'),
       ('Revere'),
       ('Rival'),
       ('River City Clocks'),
       ('Rizzy Home'),
       ('Ronco'),
       ('RoomMates'),
       ('Root'),
       ('R.S.V.P.'),
       ('Rubbermaid'),
       ('Russ'),
       ('Russell Hobbs'),
       ('SAC'),
       ('Saeco'),
       ('Saladmaster'),
       ('Salton'),
       ('Samson'),
       ('Samsung'),
       ('Sandicast'),
       ('Sanyo'),
       ('Sarah Peyton'),
       ('Satya'),
       ('Scentier'),
       ('Scentsy'),
       ('Schneider'),
       ('Sears'),
       ('Seda France'),
       ('Seiko'),
       ('Senseo'),
       ('Sensio'),
       ('SFERRA'),
       ('Shabby Chic'),
       ('Sharp'),
       ('Sharper Image'),
       ('Showtime'),
       ('Si Lucia'),
       ('SimpleHuman'),
       ('Slatkin & Co.'),
       ('Slim Line'),
       ('Snuggie'),
       ('Southern Enterprises'),
       ('Southern Living'),
       ('South Shore'),
       ('Spectrum'),
       ('SPI Home'),
       ('Stanley'),
       ('Starbucks'),
       ('Sterling Industries'),
       ('Sunbeam'),
       ('Sunrise Creek'),
       ('Swarovski'),
       ('Swing'),
       ('Syroco'),
       ('Tag'),
       ('Target'),
       ('Tassimo'),
       ('Taylor'),
       ('Teleflora'),
       ('T-fal'),
       ('The Body Shop'),
       ('The Magic Bullet'),
       ('The Northwest Company'),
       ('Thermos'),
       ('Tiger'),
       ('TimeMist'),
       ('Timex'),
       ('Toastess'),
       ('Toastmaster'),
       ('Tommy Hilfiger'),
       ('Tools of the Trade'),
       ('Trend Lab'),
       ('Tribest'),
       ('Tripar'),
       ('Trudeau'),
       ('Tupperware'),
       ('Umbra'),
       ('Unique Creations'),
       ('Update International'),
       ('Urban Trends'),
       ('Uttermost'),
       ('Vance Kitira'),
       ('Vera Bradley'),
       ('Vera Wang'),
       ('Versace'),
       ('Vickerman'),
       ('Viking'),
       ('Village Wrought Iron'),
       ('VillaWare'),
       ('Vitamix'),
       ('Vollrath'),
       ('Votivo'),
       ('Wallies'),
       ('Wall Pops'),
       ('Walls'),
       ('Waring'),
       ('Waterford'),
       ('Waverly'),
       ('WearEver'),
       ('Wedgwood'),
       ('Weight Watchers'),
       ('West Bend'),
       ('Westclox'),
       ('West Elm'),
       ('Weston'),
       ('Whirlpool'),
       ('White Mountain'),
       ('Wild Berry'),
       ('Williams Sonoma'),
       ('Willow Tree'),
       ('Wilton'),
       ('Winsome Wood'),
       ('Wolfgang Puck'),
       ('Womar Glass'),
       ('WoodWick'),
       ('Wusthof'),
       ('Wyndham House'),
       ('Yankee Candle'),
       ('Zodax'),
       ('Zojirushi'),
       ('Abu Garcia'),
       ('Adams Golf'),
       ('Adidas'),
       ('Adrenaline'),
       ('Airhead'),
       ('Airwalk'),
       ('anon'),
       ('Aqua Lung Sport'),
       ('ASICS'),
       ('Babolat'),
       ('Barnett Crossbows'),
       ('Barska'),
       ('Bates'),
       ('Bauer'),
       ('Bear Archery'),
       ('BEARPAW'),
       ('Berkley'),
       ('Body-Solid'),
       ('BOGS'),
       ('Bowflex'),
       ('Bridgestone Golf'),
       ('Brine'),
       ('Brooks'),
       ('Browning'),
       ('Brute'),
       ('Burton'),
       ('Bushnell'),
       ('Callaway'),
       ('CamelBak'),
       ('Camp Chef'),
       ('Canari'),
       ('Capezio'),
       ('CargoLoc'),
       ('Carhartt'),
       ('Cascade'),
       ('CCM'),
       ('Century'),
       ('Cleveland Golf'),
       ('Cliff Keen'),
       ('Cobra'),
       ('Columbia'),
       ('Comfort Zone'),
       ('CranBarry'),
       ('Crocs'),
       ('Crosman'),
       ('Cutters'),
       ('Danner'),
       ('DBX'),
       ('DC Shoes'),
       ('deBeer'),
       ('DeMarini'),
       ('Diadora'),
       ('Diamondback'),
       ('Dita'),
       ('Dolfin Swim'),
       ('Dragon'),
       ('Duck Commander'),
       ('Dunlop'),
       ('Durango'),
       ('Easton'),
       ('Ecco'),
       ('E-Force'),
       ('Ektelon'),
       ('elite HOCKEY'),
       ('EPIC'),
       ('EP Pro'),
       ('Eureka!'),
       ('Everlast'),
       ('EvoShield'),
       ('Exerpeutic'),
       ('Field & Stream'),
       ('Fitbit'),
       ('Fitness Gear'),
       ('Fit Win'),
       ('Flow Society'),
       ('FootJoy'),
       ('Franklin'),
       ('Frogger'),
       ('Future Beach'),
       ('GAIAM'),
       ('Gamma'),
       ('Gamo'),
       ('Garmin'),
       ('Gatorade'),
       ('Gearbox'),
       ('Gerber'),
       ('Giro'),
       ('Glamorise'),
       ('G. Loomis'),
       ('Glove It'),
       ('Goaliath'),
       ('Goalrilla'),
       ('GolfBuddy'),
       ('Golf Pride'),
       ('GoPro'),
       ('GORE-TEX'),
       ('Grays'),
       ('Gregory'),
       ('Harrow'),
       ('HEAD'),
       ('Helly Hansen'),
       ('High Sierra'),
       ('HO'),
       ('Horizon'),
       ('Humminbird'),
       ('Hurley'),
       ('HYPERion'),
       ('Hyperlite'),
       ('Impex'),
       ('Inov-'),
       ('Itech'),
       ('Jamie Sadock'),
       ('JanSport'),
       ('Jockey'),
       ('Jordan'),
       ('JUGS Sports'),
       ('KEEN'),
       ('Kelty'),
       ('Keys'),
       ('Kijaro'),
       ('KOPPEN'),
       ('Lady Hagen'),
       ('Lamkin'),
       ('Landice'),
       ('Leupold'),
       ('Life Is Good'),
       ('Lifetime'),
       ('Lobster'),
       ('Lole'),
       ('Louisville Slugger'),
       ('Lowrance'),
       ('lucy'),
       ('Manduka'),
       ('Marmot'),
       ('Marucci'),
       ('Maui Jim'),
       ('Maverik'),
       ('Maxfli'),
       ('McDavid'),
       ('Merrell'),
       ('Mission'),
       ('Mitre'),
       ('Mizuno'),
       ('Mountain Hardwear'),
       ('Moving Comfort'),
       ('Mueller'),
       ('Muzzy Broadheads'),
       ('Mylec'),
       ('Nancy Lopez'),
       ('Nathan'),
       ('Natural Fitness'),
       ('Nautilus'),
       ('New Balance'),
       ('Nickent'),
       ('Nike'),
       ('Nike Golf'),
       ('Nike Swim'),
       ('Nikon'),
       ('Nishik'),
       ('Oakley'),
       ('O''Brien Ocean Minded'),
       ('Odyssey'),
       ('OGIO'),
       ('Old Town'),
       ('O''Neill Patagonia'),
       ('Pearl Izumi'),
       ('Pelican'),
       ('Penn Fishing'),
       ('Perception Sport'),
       ('PING'),
       ('Pinnacle Fishing'),
       ('Potomac'),
       ('Powerbolt'),
       ('prAna'),
       ('Precor'),
       ('Primed'),
       ('Prince'),
       ('Princeton Tec'),
       ('ProForm'),
       ('PTEX'),
       ('PUMA'),
       ('Quantum'),
       ('Quiksilver'),
       ('Rage Broadheads'),
       ('Rage Fitness Supply'),
       ('Rainbow'),
       ('Ram'),
       ('Rawlings'),
       ('Razor'),
       ('RBK'),
       ('Redington'),
       ('Reebok'),
       ('Reef'),
       ('Reusch'),
       ('Riddell'),
       ('ROCKY'),
       ('Rollerblade'),
       ('Roller Derby'),
       ('Rossignol'),
       ('Roxy'),
       ('Royal Robbins'),
       ('Running Skirts'),
       ('Russell Athletic'),
       ('Salomon'),
       ('Saucony'),
       ('ScentBlocker'),
       ('Schutt'),
       ('Schwinn'),
       ('Sea Eagle'),
       ('Select'),
       ('Shimano Fishing'),
       ('Shock Absorber'),
       ('Shock Doctor'),
       ('SKINS'),
       ('SKLZ'),
       ('SkyCaddie'),
       ('Slazenger'),
       ('SmartWool'),
       ('Smith Optics'),
       ('Soffe'),
       ('Sof Sole'),
       ('SOLE'),
       ('Sorel'),
       ('Spalding'),
       ('Speedo'),
       ('Sperry Top-Sider'),
       ('SPY'),
       ('Spyder'),
       ('Srixon'),
       ('Stack-On'),
       ('Stamina'),
       ('St. Croix'),
       ('Stick-e'),
       ('Stiga'),
       ('STOTT PILATES'),
       ('STX'),
       ('Sun Mountain'),
       ('Superfeet'),
       ('Super Stroke'),
       ('Swami'),
       ('Swix'),
       ('Tachikara'),
       ('Tail'),
       ('TaylorMade'),
       ('Teeter Hang Ups'),
       ('TenPoint'),
       ('TETON Sports'),
       ('The North Face'),
       ('The Original Muck Boot Co.'),
       ('Thrive'),
       ('Thule'),
       ('Timberland'),
       ('Titleist'),
       ('Top Flite'),
       ('UFC'),
       ('UGG Australia'),
       ('Umbro'),
       ('Under Armour'),
       ('USA Hockey'),
       ('Volcom'),
       ('Walter Hagen'),
       ('Warrior'),
       ('Wilson'),
       ('Wolverine'),
       ('Worth'),
       ('Wright & McGill'),
       ('Xenith'),
       ('XU'),
       ('Yakima'),
       ('Yeti'),
       ('Zaggora'),
       ('Zoggs'),
       ('Acer'),
       ('Acoustic Research'),
       ('Advent'),
       ('Agfa'),
       ('Aiptek'),
       ('Allsop'),
       ('Altec Lansing'),
       ('AmazonBasics'),
       ('AMD'),
       ('Apple'),
       ('Archos'),
       ('ASUS'),
       ('ATI Technologies'),
       ('AudioSource'),
       ('Audio-Technica'),
       ('Audiovox'),
       ('Avery'),
       ('Bang & Olufsen'),
       ('Beats'),
       ('Belkin'),
       ('Beltronics'),
       ('Benwin'),
       ('Best Data Products'),
       ('Body Glove'),
       ('Bose'),
       ('Brother'),
       ('Brunton'),
       ('Bulldog Security'),
       ('Canon'),
       ('Card Access'),
       ('CardScan'),
       ('Castlewood Systems'),
       ('CD Projects'),
       ('Cherokee'),
       ('CMC Magnetics'),
       ('Com'),
       ('Command Communications'),
       ('Compaq'),
       ('Compex'),
       ('Contour'),
       ('Creative Labs'),
       ('Curtis Computer Products'),
       ('Dazzle Multimedia'),
       ('Delkin'),
       ('Dell'),
       ('DeLorme'),
       ('Denon'),
       ('dfx'),
       ('DIRECTV'),
       ('DiscRestore International'),
       ('DivX'),
       ('D-Link'),
       ('DYMO'),
       ('Ear Hugger'),
       ('Ectaco'),
       ('Eiger Labs'),
       ('Emachines'),
       ('Energizer'),
       ('Entrega Technologies'),
       ('Epson'),
       ('Escort Radar'),
       ('Eveready'),
       ('EXP Computer'),
       ('Ezonics'),
       ('Fisher'),
       ('Franklin Electronics'),
       ('Fuji'),
       ('Gateway'),
       ('GBC'),
       ('General Electric'),
       ('Genica'),
       ('Genovation'),
       ('GeoDiscovery'),
       ('Glenayre'),
       ('Go Gear'),
       ('Good Technology'),
       ('GPX'),
       ('Gravis'),
       ('Griffin'),
       ('Grundig'),
       ('Hannspree'),
       ('Harman Kardon'),
       ('HP'),
       ('HTC'),
       ('IBM'),
       ('I-Jam'),
       ('Imation'),
       ('Incase Designs'),
       ('Incipio'),
       ('InnoGear'),
       ('Insignia'),
       ('Intel'),
       ('InterAct'),
       ('Interex'),
       ('Invent It'),
       ('Iogear'),
       ('JBL'),
       ('Jeep'),
       ('Jensen'),
       ('JVC'),
       ('Karrier Communications'),
       ('Kash Gold'),
       ('KDS'),
       ('Kensington'),
       ('Kenwood'),
       ('KLH'),
       ('Klipsch'),
       ('Kodak'),
       ('Koss'),
       ('Labtec'),
       ('LaCie'),
       ('LandWare'),
       ('LaserLine'),
       ('Laserlyte'),
       ('Lexar'),
       ('LG'),
       ('Linksys'),
       ('Logitech'),
       ('Magellan'),
       ('Magnavox'),
       ('MartinLogan'),
       ('Maxell'),
       ('Maxtor'),
       ('Micro Innovations'),
       ('Microsoft'),
       ('Microtek'),
       ('Midland'),
       ('Mitsubishi'),
       ('Monster Cable'),
       ('Motion Systems'),
       ('NEC Technologies'),
       ('Netgear'),
       ('New Media Tech'),
       ('Nintendo'),
       ('Nokia'),
       ('OmniSky'),
       ('On-Hold Plus'),
       ('Onkyo'),
       ('OnStream'),
       ('Oregon Scientific'),
       ('PDA Panache'),
       ('Phillips'),
       ('Phonex'),
       ('Pine Technology'),
       ('Pinnacle Systems'),
       ('Pioneer'),
       ('Plantronics'),
       ('PNY'),
       ('PoGo! Products'),
       ('Polk Audio'),
       ('Polycom'),
       ('Precision Navigation'),
       ('Princeton'),
       ('Psion'),
       ('Q-See'),
       ('Rand McNally'),
       ('Razer'),
       ('Recoton'),
       ('Refac'),
       ('RhinoSkin'),
       ('Ridata'),
       ('RIM'),
       ('Roku'),
       ('Royal'),
       ('Saitek'),
       ('Samsonite'),
       ('SanDisk'),
       ('Sangean'),
       ('Seagate'),
       ('Seiko Instruments'),
       ('Sennheiser'),
       ('Sensory Science'),
       ('Sherwood'),
       ('Shure'),
       ('Siemens'),
       ('Sirius Satellite Radio'),
       ('Socket Communications'),
       ('Sony'),
       ('Southwestern Bell'),
       ('SportBrain'),
       ('Sumdex'),
       ('Suunto'),
       ('Swatch'),
       ('Sylvania'),
       ('Targus'),
       ('TDK'),
       ('Teac'),
       ('Technics'),
       ('Texas Instruments'),
       ('Thomson Consumer Electronics'),
       ('TiVo'),
       ('Tivoli'),
       ('TomTom'),
       ('Toshiba'),
       ('TravRoute'),
       ('Tripp Lite'),
       ('UltimateTV RCA'),
       ('Umax'),
       ('Uniden'),
       ('Unwired Technologies'),
       ('Velocity'),
       ('ViewSonic'),
       ('Visioneer'),
       ('Vivonic'),
       ('VTech'),
       ('VXI'),
       ('Wacom'),
       ('Western Digital'),
       ('Wharfedale'),
       ('Whistler Radar'),
       ('Xbox'),
       ('XM'),
       ('Yamaha'),
       ('Zoom'),
       ('Zune'),
       ('ZyXEL'),
       ('Alexandra de Markoff'),
       ('Almay'),
       ('Arbonne'),
       ('Ardell'),
       ('Aveda'),
       ('Bare Escentuals'),
       ('BeautiControl'),
       ('Benefit'),
       ('Blinc'),
       ('Bobbi Brown'),
       ('Bonne Bell'),
       ('Borghese'),
       ('Bourjois'),
       ('Burt''s Bees'),
       ('Chanel'),
       ('Christian Dior'),
       ('Clarins'),
       ('Clinique'),
       ('Coty'),
       ('CoverGirl'),
       ('Dermablend'),
       ('DuWop'),
       ('e.l.f.'),
       ('Elizabeth Arden'),
       ('eos'),
       ('Estee Lauder'),
       ('Fashion Fair'),
       ('Georgio Armani'),
       ('Givenchy'),
       ('GloMinerals'),
       ('Guerlain'),
       ('Hard Candy'),
       ('Inner Beauty'),
       ('Jafra'),
       ('Jane Iredale'),
       ('Kanebo'),
       ('Kat Von D'),
       ('Kiehl''s Lancome'),
       ('Laura Geller'),
       ('Laura Mercier'),
       ('Lola'),
       ('L''Oreal Lorac'),
       ('MAC'),
       ('Mally Beauty'),
       ('Manic Panic'),
       ('MARC JACOBS'),
       ('Mary Kay'),
       ('Max Factor'),
       ('Maybelline'),
       ('Milani'),
       ('Nars'),
       ('Neutrogena'),
       ('Nina Ricci'),
       ('NYX'),
       ('Origins'),
       ('Physicians Formula'),
       ('Pop Beauty'),
       ('Prescriptives'),
       ('% Pure'),
       ('Red Cherry'),
       ('Revlon'),
       ('Rimmel'),
       ('Sally Hansen');