insert into public.catalogue (catalogue_id, url, image, parent_id, name)
values  (1, 'smartfony', 'smartfony-image.jpg', 1, 'Смартфоны'),
        (2, 'premium-smartfony', 'premium-smartfony-image.jpg', 1, 'Премиум смартфоны'),
        (3, 'apple-iphone', 'apple-iphone-image.jpg', 1, 'APPLE iPhone'),
        (4, 'smartfony-huawei', 'smartfony-huawei-image.jpg', 1, 'Смартфоны HUAWEI'),
        (5, 'smartfony-samsung', 'smartfony-samsung-image.jpg', 1, 'Смартфоны SAMSUNG'),
        (6, 'smartfony-xiaomi', 'smartfony-xiaomi-image.jpg', 1, 'Смартфоны XIAOMI'),
        (7, 'smartfony-realme', 'smartfony-realme-image.jpg', 1, 'Смартфоны REALME'),
        (8, 'smartfony-honor', 'smartfony-honor-image.jpg', 1, 'Смартфоны HONOR'),
        (9, 'smartfony-infinix', 'smartfony-infinix-image.jpg', 1, 'Смартфоны INFINIX'),
        (10, 'smartfony-tecno', 'smartfony-tecno-image.jpg', 1, 'Смартфоны TECNO'),
        (11, 'nedorogie-smartfony', 'nedorogie-smartfony-image.jpg', 1, 'Недорогие смартфоны'),
        (12, 'smartfony-na-android', 'smartfony-na-android-image.jpg', 1, 'Смартфоны на Android'),
        (13, 'naushniki', 'naushniki-image.jpg', 13, 'Наушники'),
        (14, 'naushniki-anker-soundcore', 'naushniki-anker-soundcore-image.jpg', 13, 'Наушники ANKER Soundcore'),
        (15, 'besprovodnye-naushniki', 'besprovodnye-naushniki-image.jpg', 13, 'Беспроводные наушники'),
        (16, 'tws-naushniki', 'tws-naushniki-image.jpg', 13, 'TWS наушники'),
        (17, 'monitornye-naushniki', 'monitornye-naushniki-image.jpg', 13, 'Мониторные наушники'),
        (18, 'naushniki-vkladyshi', 'naushniki-vkladyshi-image.jpg', 13, 'Наушники вкладыши'),
        (19, 'provodnye-naushniki', 'provodnye-naushniki-image.jpg', 13, 'Проводные наушники'),
        (20, 'nakladnye-naushniki', 'nakladnye-naushniki-image.jpg', 13, 'Накладные наушники'),
        (21, 'naushniki-digma', 'naushniki-digma-image.jpg', 13, 'Наушники DIGMA'),
        (22, 'naushniki-oklick', 'naushniki-oklick-image.jpg', 13, 'Наушники Oklick'),
        (23, 'nedorogie-naushniki', 'nedorogie-naushniki-image.jpg', 13, 'Недорогие наушники'),
        (24, 'sportivnye-naushniki', 'sportivnye-naushniki-image.jpg', 13, 'Спортивные наушники'),
        (25, 'gadzhety', 'gadzhety-image.jpg', 25, 'Гаджеты'),
        (26, 'smart-chasy', 'smart-chasy-image.jpg', 25, 'Смарт-часы'),
        (27, 'detskie-smart-chasy', 'detskie-smart-chasy-image.jpg', 25, 'Детские смарт-часы'),
        (28, 'kvadrokoptery', 'kvadrokoptery-image.jpg', 25, 'Квадрокоптеры'),
        (29, 'fitnes-braslety', 'fitnes-braslety-image.jpg', 25, 'Фитнес-браслеты'),
        (30, 'ekshn-kamery', 'ekshn-kamery-image.jpg', 25, 'Экшн-камеры'),
        (31, 'tcifrovye-fotoramki', 'tcifrovye-fotoramki-image.jpg', 25, 'Цифровые фоторамки'),
        (32, 'aksessuary-dlia-kvadrokopterov', 'aksessuary-dlia-kvadrokopterov-image.jpg', 25, 'Аксессуары для квадрокоптеров'),
        (33, 'aksessuary-dlia-smart-chasov', 'aksessuary-dlia-smart-chasov-image.jpg', 25, 'Аксессуары для смарт-часов'),
        (34, 'kvadrokoptery-i-aksessuary', 'kvadrokoptery-i-aksessuary-image.jpg', 25, 'Квадрокоптеры и аксессуары'),
        (35, 'elektrotransport', 'elektrotransport-image.jpg', 25, 'Электротранспорт'),
        (36, 'ratcii', 'ratcii-image.jpg', 25, 'Рации'),
        (37, 'aksessuary-dlia-ratcii', 'aksessuary-dlia-ratcii-image.jpg', 25, 'Аксессуары для раций'),
        (38, 'noutbuki', 'noutbuki-image.jpg', 38, 'Ноутбуки'),
        (39, 'nedorogie-noutbuki', 'nedorogie-noutbuki-image.jpg', 38, 'Недорогие ноутбуки'),
        (40, 'igrovye-noutbuki', 'igrovye-noutbuki-image.jpg', 38, 'Игровые ноутбуки'),
        (41, 'ultrabuki', 'ultrabuki-image.jpg', 38, 'Ультрабуки'),
        (42, 'noutbuki-transformery', 'noutbuki-transformery-image.jpg', 38, 'Ноутбуки-трансформеры'),
        (43, 'noutbuki-huawei', 'noutbuki-huawei-image.jpg', 38, 'Ноутбуки Huawei'),
        (44, 'noutbuki-apple', 'noutbuki-apple-image.jpg', 38, 'Ноутбуки Apple'),
        (45, 'televizory', 'televizory-image.jpg', 45, 'Телевизоры'),
        (46, 'televizory-oled', 'televizory-oled-image.jpg', 45, 'Телевизоры OLED'),
        (47, 'televizory-neo-qled', 'televizory-neo-qled-image.jpg', 45, 'Телевизоры NEO QLED'),
        (48, 'televizory-crystal-uhd', 'televizory-crystal-uhd-image.jpg', 45, 'Телевизоры Crystal UHD'),
        (49, 'televizory-nanocell', 'televizory-nanocell-image.jpg', 45, 'Телевизоры NanoCell'),
        (50, 'televizory-hyundai', 'televizory-hyundai-image.jpg', 45, 'Телевизоры Hyundai'),
        (51, 'smart-tv', 'smart-tv-image.jpg', 45, 'Смарт ТВ'),
        (52, 'televizory-ultra-hd-4k', 'televizory-ultra-hd-4k-image.jpg', 45, 'Телевизоры Ultra HD 4K'),
        (53, 'televizory-ultra-hd-8k', 'televizory-ultra-hd-8k-image.jpg', 45, 'Телевизоры Ultra HD 8K'),
        (54, 'audiotekhnika', 'audiotekhnika-image.jpg', 54, 'Аудиотехника'),
        (55, 'portativnye-kolonki', 'portativnye-kolonki-image.jpg', 54, 'Портативные колонки'),
        (56, 'saundbary', 'saundbary-image.jpg', 54, 'Саундбары'),
        (57, 'muzykalnye-tcentry', 'muzykalnye-tcentry-image.jpg', 54, 'Музыкальные центры'),
        (58, 'magnitoly', 'magnitoly-image.jpg', 54, 'Магнитолы'),
        (98, 'wi-fi-kamery', 'wi-fi-kamery-image.jpg', 82, 'Wi-Fi камеры'),
        (59, 'kolonki-dlia-kompiutera', 'kolonki-dlia-kompiutera-image.jpg', 54, 'Колонки для компьютера'),
        (60, 'mp3-pleery', 'mp3-pleery-image.jpg', 54, 'MP3 плееры'),
        (61, 'diktofony', 'diktofony-image.jpg', 54, 'Диктофоны'),
        (62, 'mikrofony', 'mikrofony-image.jpg', 54, 'Микрофоны'),
        (63, 'radiobudilniki', 'radiobudilniki-image.jpg', 54, 'Радиобудильники'),
        (64, 'radiopriemniki', 'radiopriemniki-image.jpg', 54, 'Радиоприемники'),
        (65, 'radiosistemy', 'radiosistemy-image.jpg', 54, 'Радиосистемы'),
        (66, 'spikerfony', 'spikerfony-image.jpg', 54, 'Спикерфоны'),
        (67, 'umnye-kolonki', 'umnye-kolonki-image.jpg', 54, 'Умные колонки'),
        (68, 'umnye-kolonki-s-alisoi', 'umnye-kolonki-s-alisoi-image.jpg', 54, 'Умные колонки с Алисой'),
        (69, 'muzykalnye-tcentry-s-karaoke', 'muzykalnye-tcentry-s-karaoke-image.jpg', 54, 'Музыкальные центры с караоке'),
        (70, 'krupnaia-bytovaia-tekhnika', 'krupnaia-bytovaia-tekhnika-image.jpg', 70, 'Крупная бытовая техника'),
        (71, 'vinnye-shkafy', 'vinnye-shkafy-image.jpg', 70, 'Винные шкафы'),
        (72, 'kholodilniki', 'kholodilniki-image.jpg', 70, 'Холодильники'),
        (73, 'stiralnye-mashiny', 'stiralnye-mashiny-image.jpg', 70, 'Стиральные машины'),
        (74, 'sushilnye-mashiny', 'sushilnye-mashiny-image.jpg', 70, 'Сушильные машины'),
        (75, 'nastolnye-plity', 'nastolnye-plity-image.jpg', 70, 'Настольные плиты'),
        (76, 'gazovye-plity', 'gazovye-plity-image.jpg', 70, 'Газовые плиты'),
        (77, 'elektricheskie-plity', 'elektricheskie-plity-image.jpg', 70, 'Электрические плиты'),
        (78, 'posudomoechnye-mashiny', 'posudomoechnye-mashiny-image.jpg', 70, 'Посудомоечные машины'),
        (79, 'morozilnye-kamery', 'morozilnye-kamery-image.jpg', 70, 'Морозильные камеры'),
        (80, 'morozilnye-lari', 'morozilnye-lari-image.jpg', 70, 'Морозильные лари'),
        (81, 'kholodilniki-dlia-dachi', 'kholodilniki-dlia-dachi-image.jpg', 70, 'Холодильники для дачи'),
        (82, 'umnyi-dom', 'umnyi-dom-image.jpg', 82, 'Умный дом'),
        (83, 'umnye-kolonki', 'umnye-kolonki-image.jpg', 82, 'Умные колонки'),
        (84, 'umnye-rozetki', 'umnye-rozetki-image.jpg', 82, 'Умные розетки'),
        (85, 'umnye-lampy', 'umnye-lampy-image.jpg', 82, 'Умные лампы'),
        (86, 'umnye-svetilniki', 'umnye-svetilniki-image.jpg', 82, 'Умные светильники'),
        (87, 'datchiki-dlia-umnogo-doma', 'datchiki-dlia-umnogo-doma-image.jpg', 82, 'Датчики для умного дома'),
        (88, 'tcentry-upravleniia-umnym-domom', 'tcentry-upravleniia-umnym-domom-image.jpg', 82, 'Центры управления умным домом'),
        (89, 'umnye-vykliuchateli', 'umnye-vykliuchateli-image.jpg', 82, 'Умные выключатели'),
        (90, 'umnye-pulty-i-knopki', 'umnye-pulty-i-knopki-image.jpg', 82, 'Умные пульты и кнопки'),
        (91, 'umnye-rele-i-moduli-upravleniia', 'umnye-rele-i-moduli-upravleniia-image.jpg', 82, 'Умные реле и модули управления'),
        (92, 'umnye-svetodiodnye-lenty', 'umnye-svetodiodnye-lenty-image.jpg', 82, 'Умные светодиодные ленты'),
        (93, 'komplekty-umnogo-doma', 'komplekty-umnogo-doma-image.jpg', 82, 'Комплекты умного дома'),
        (94, 'umnye-zamki', 'umnye-zamki-image.jpg', 82, 'Умные замки'),
        (95, 'umnye-karnizy,-shtory-i-komplektuiushchie', 'umnye-karnizy,-shtory-i-komplektuiushchie-image.jpg', 82, 'Умные карнизы, шторы и комплектующие'),
        (96, 'umnye-ustroistva-dlia-zhivotnykh', 'umnye-ustroistva-dlia-zhivotnykh-image.jpg', 82, 'Умные устройства для животных'),
        (97, 'moduli-dlia-umnykh-ustroistv', 'moduli-dlia-umnykh-ustroistv-image.jpg', 82, 'Модули для умных устройств'),
        (99, 'okhrannye-signalizatcii', 'okhrannye-signalizatcii-image.jpg', 82, 'Охранные сигнализации'),
        (100, 'umnye-televizory', 'umnye-televizory-image.jpg', 82, 'Умные телевизоры'),
        (101, 'roboty-pylesosy', 'roboty-pylesosy-image.jpg', 82, 'Роботы-пылесосы'),
        (102, 'umnye-chainiki', 'umnye-chainiki-image.jpg', 82, 'Умные чайники');