with data as (select column1 as url, column2 as name, column3 as description, column4 as type, column5 as image
              from (values ('ocean-blue-shirt',
                            'Ocean Blue Shirt',
                            'Ocean blue cotton shirt with a narrow collar and buttons down the front and long sleeves. Comfortable fit and tiled kalidoscope patterns. ',
                            'clothes',
                            'https://burst.shopifycdn.com/photos/young-man-in-bright-fashion_925x.jpg'),
                           ('classic-varsity-top', 'Classic Varsity Top',
                            'Womens casual varsity top, This grey and black buttoned top is a sport-inspired piece complete with an embroidered letter. ',
                            'clothes', 'https://burst.shopifycdn.com/photos/casual-fashion-woman_925x.jpg'),
                           ('yellow-wool-jumper', 'Yellow Wool Jumper',
                            'Knitted jumper in a soft wool blend with low dropped shoulders and wide sleeves and think cuffs. Perfect for keeping warm during Fall. ',
                            'clothes',
                            'https://burst.shopifycdn.com/photos/autumn-photographer-taking-picture_925x.jpg'),
                           ('floral-white-top', 'Floral White Top',
                            'Stylish sleeveless white top with a floral pattern. ', 'clothes',
                            'https://burst.shopifycdn.com/photos/city-woman-fashion_925x@2x.jpg'),
                           ('striped-silk-blouse', 'Striped Silk Blouse',
                            'Ultra-stylish black and red striped silk blouse with buckle collar and matching button pants. ',
                            'clothes',
                            'https://burst.shopifycdn.com/photos/striped-blouse-fashion_925x.jpg'),
                           ('classic-leather-jacket', 'Classic Leather Jacket',
                            'Womans zipped leather jacket. Adjustable belt for a comfortable fit, complete with shoulder pads and front zip pocket. ',
                            'clothes', 'https://burst.shopifycdn.com/photos/leather-jacket-and-tea_925x.jpg'),
                           ('dark-denim-top', 'Dark Denim Top',
                            'Classic dark denim top with chest pockets, long sleeves with buttoned cuffs, and a ripped hem effect.',
                            'clothes', 'https://burst.shopifycdn.com/photos/young-female-models-denim_925x.jpg'),
                           ('navy-sport-jacket', 'Navy Sports Jacket',
                            'Long-sleeved navy waterproof jacket in thin, polyester fabric with a soft mesh inside. The ',
                            'clothes',
                            'https://burst.shopifycdn.com/photos/mens-fall-fashion-jacket_925x.jpg'),
                           ('dark-winter-jacket', 'Soft Winter Jacket',
                            'Thick black winter jacket, with soft fleece lining. Perfect for those cold weather days.',
                            'clothes',
                            'https://burst.shopifycdn.com/photos/smiling-woman-on-snowy-afternoon_925x.jpg'),
                           ('black-leather-bag', 'Black Leather Bag',
                            'Womens black leather bag, with ample space. Can be worn over the shoulder, or remove straps to carry in your hand. ',
                            'clothes', 'https://burst.shopifycdn.com/photos/black-bag-over-the-shoulder_925x.jpg'),
                           ('zipped-jacket', 'Zipped Jacket',
                            'Dark navy and light blue men''s zipped waterproof jacket with an outer zipped chestpocket for easy storeage.',
                            'clothes', 'https://burst.shopifycdn.com/photos/menswear-blue-zip-up-jacket_925x.jpg'),
                           ('silk-summer-top', 'Silk Summer Top',
                            'Silk womens top with short sleeves and number pattern.', 'clothes',
                            'https://burst.shopifycdn.com/photos/young-hip-woman-at-carnival_925x.jpg'),
                           ('longsleeve-cotton-top', 'Long Sleeve Cotton Top',
                            'Black cotton womens top, with long sleeves, no collar and a thick hem. ', 'clothes',
                            'https://burst.shopifycdn.com/photos/woman-outside-brownstone_925x.jpg'),
                           ('chequered-red-shirt', 'Chequered Red Shirt',
                            'Classic mens plaid flannel shirt with long sleeves, in chequered style, with two chest pockets.',
                            'clothes',
                            'https://burst.shopifycdn.com/photos/red-plaid-shirt_925x.jpg'),
                           ('white-cotton-shirt', 'White Cotton Shirt',
                            'Plain white cotton long sleeved shirt with loose collar. Small buttons and front pocket. ',
                            'clothes',
                            'https://burst.shopifycdn.com/photos/smiling-woman-poses_925x.jpg'),
                           ('olive-green-jacket', 'Olive Green Jacket',
                            'Loose fitting olive green jacket with buttons and large pockets. Multicoloured pattern on the front of the shoulders.',
                            'clothes', 'https://burst.shopifycdn.com/photos/urban-fashion_925x.jpg'),
                           ('blue-silk-tuxedo', 'Blue Silk Tuxedo',
                            'Blue silk tuxedo with marbled aquatic pattern and dark lining. Sleeves are complete with rounded hem and black buttons.',
                            'clothes', 'https://burst.shopifycdn.com/photos/man-adjusts-blue-tuxedo-bowtie_925x.jpg'),
                           ('red-sports-tee', 'Red Sports Tee',
                            'Women''s red sporty t-shirt with colorful details on the sleeves and a small white pocket.',
                            'clothes',
                            'https://burst.shopifycdn.com/photos/womens-red-t-shirt_925x.jpg'),
                           ('striped-skirt-and-top', 'Striped Skirt and Top',
                            'Black cotton top with matching striped skirt. ',
                            'clothes',
                            'https://burst.shopifycdn.com/photos/woman-in-the-city_925x.jpg'),
                           ('led-high-tops', 'LED High Tops',
                            'Black high top shoes with green LED lights in the sole, tied up with laces and a buckle. ',
                            'clothes',
                            'https://burst.shopifycdn.com/photos/putting-on-your-shoes_925x.jpg'),
                           ('clay-plant-pot', 'Clay Plant Pot', '<p>Classic blown clay pot for plants</p>', 'Outdoor',
                            'https://burst.shopifycdn.com/photos/single-sprout-in-a-pot_925x.jpg'),
                           ('copper-light', 'Copper Light', '<p>Stylish copper bedside light</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/copper-light-in-bedroom_925x.jpg'),
                           ('cream-sofa', 'Cream Sofa', '<p>Comfortable cream sofa with wooden base</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/condominium-interior-livingroom_925x.jpg'),
                           ('antique-drawers', 'Antique Drawers', '<p>Antique wooden chest of drawers</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/babys-room_925x.jpg'),
                           ('white-bed-clothes', 'White Bed Clothes', '<p>Sleek white bed clothes</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/bright-hotel-room-bed_925x.jpg'),
                           ('pink-armchair', 'Pink Armchair', '<p>Stylish pink armchair</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/soft-pink-cushioned-armchair-in-stately-salon_925x.jpg'),
                           ('wooden-outdoor-table', 'Wooden Outdoor Table', '<p>Chic wooden outdoor garden table</p>',
                            'Outdoor',
                            'https://burst.shopifycdn.com/photos/cafe-patio_925x.jpg'),
                           ('brown-throw-pillows', 'Brown Throw Pillows', '<p>Stylish brown throw pillows</p>',
                            'Indoor',
                            'https://burst.shopifycdn.com/photos/bedroom-bed-with-brown-throw-pillows_925x.jpg'),
                           ('white-ceramic-pot', 'White Ceramic Pot', '<p>Homemade white ceramic flower pot</p>',
                            'Indoor',
                            'https://burst.shopifycdn.com/photos/house-plant-in-white-pot_925x.jpg'),
                           ('yellow-watering-can', 'Yellow watering can', '<p>Vintage vibrant watering can</p>',
                            'Outdoor',
                            'https://burst.shopifycdn.com/photos/flowers-in-yellow-watering-can_925x.jpg'),
                           ('gardening-hand-trowel', 'Gardening hand trowel',
                            '<p>Metal gardening hand trowel with wooden handle</p>',
                            'Outdoor', 'https://burst.shopifycdn.com/photos/spring-gardening-set-up_925x.jpg'),
                           ('biodegradable-cardboard-pots', 'Biodegradable cardboard pots',
                            '<p>Biodegradable outdoor cardboard pots</p>',
                            'Outdoor', 'https://burst.shopifycdn.com/photos/potted-seeds_925x.jpg'),
                           ('grey-sofa', 'Grey Sofa', '<p>Large four seater grey sofa</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/large-grey-sofa-by-brick-wall_925x.jpg'),
                           ('wooden-outdoor-slats', 'Wooden outdoor slats', '<p>Wooden outdoor fencing slats</p>',
                            'Outdoor',
                            'https://burst.shopifycdn.com/photos/house-plant-on-wooden-slat-wall_925x.jpg'),
                           ('wooden-fence', 'Wooden Fence', '<p>Wooden garden fence</p>', 'Outdoor',
                            'https://burst.shopifycdn.com/photos/picket-fence-flowers_925x.jpg'),
                           ('yellow-sofa', 'Yellow Sofa', '<p>Two seater yellow sofa with wooden legs</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/yellow-couch-by-black-and-white-mural_925x.jpg'),
                           ('knitted-throw-pillows', 'Knitted Throw Pillows',
                            '<p>Homemade knitted throw pillows in a variety of colors</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/yellow-sofa-with-throw-pillows_925x.jpg'),
                           ('vanilla-candle', 'Vanilla candle', '<p>Vanilla scent candle in jar</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/diy-organic-candle_925x.jpg'),
                           ('black-bean-bag', 'Black Beanbag', '<p>Black leather beanbag</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/comfortable-living-room-cat_925x.jpg'),
                           ('bedside-table', 'Bedside Table', '<p>Wooden bedside table</p>', 'Indoor',
                            'https://burst.shopifycdn.com/photos/dark-wall-bedside-table_925x.jpg'),
                           ('chain-bracelet', '7 Shakra Bracelet', '7 chakra bracelet, in blue or black.', 'Bracelet',
                            'https://burst.shopifycdn.com/photos/7-chakra-bracelet_925x.jpg'),
                           ('leather-anchor', 'Anchor Bracelet Mens',
                            'Black leather bracelet with gold or silver anchor for men.',
                            'Bracelet', 'https://burst.shopifycdn.com/photos/anchor-bracelet-mens_925x.jpg'),
                           ('bangle-bracelet', 'Bangle Bracelet', 'Gold bangle bracelet with studded jewels.',
                            'Bracelet',
                            'https://burst.shopifycdn.com/photos/bangle-bracelet-with-jewels_925x.jpg'),
                           ('bangle-bracelet-with-feathers', 'Boho Bangle Bracelet',
                            'Gold boho bangle bracelet with multicolor tassels.',
                            'Bracelet', 'https://burst.shopifycdn.com/photos/bangle-bracelet-with-feathers_925x.jpg'),
                           ('boho-earrings', 'Boho Earrings', 'Turquoise globe earrings on 14k gold hooks.', 'Earrings',
                            'https://burst.shopifycdn.com/photos/boho-earrings_925x.jpg'),
                           ('choker-with-bead', 'Choker with Bead', 'Black choker necklace with 14k gold bead.',
                            'Necklace',
                            'https://burst.shopifycdn.com/photos/black-choker-with-bead_925x.jpg'),
                           ('choker-with-gold-pendant', 'Choker with Gold Pendant',
                            'Black cord choker with gold pendant. Beautifully died black leather shapes a choker necklace with findings of 14k yellow gold.',
                            'Necklace', 'https://burst.shopifycdn.com/photos/choker-with-gold-pendant_925x.jpg'),
                           ('choker-with-triangle', 'Choker with Triangle',
                            'Black choker with silver triangle pendant.', 'Necklace',
                            'https://burst.shopifycdn.com/photos/choker-with-triangle_925x.jpg'),
                           ('dainty-gold-neclace', 'Dainty Gold Necklace', 'Dainty gold necklace with two pendants.',
                            'Necklace',
                            'https://burst.shopifycdn.com/photos/dainty-gold-necklace_925x.jpg'),
                           ('dreamcatcher-pendant-necklace', 'Dreamcatcher Pendant Necklace',
                            'Turquoise beaded dream catcher necklace. Silver feathers adorn this beautiful dream catcher, which move and twinkle as you walk.',
                            'Necklace', 'https://burst.shopifycdn.com/photos/dreamcatcher-pendant-necklace_925x.jpg'),
                           ('galaxy-earrings', 'Galaxy Earrings',
                            'One set of galaxy earrings, with sterling silver clasps.',
                            'Earrings',
                            'https://burst.shopifycdn.com/photos/galaxy-earrings_925x.jpg'),
                           ('gemstone', 'Gemstone Necklace',
                            '<p>Gemstone pendant, housed in sterling silver, with sterling silver chain.</p>',
                            'Necklace',
                            'https://burst.shopifycdn.com/photos/blue-gemstone-pendant_925x.jpg'),
                           ('gold-bird-necklace', 'Gold Bird Necklace',
                            '14k Gold delicate necklace, with bird between two chains.',
                            'Necklace', 'https://burst.shopifycdn.com/photos/gold-bird-necklace_925x.jpg'),
                           ('looped-earrings', 'Gold Elephant Earrings',
                            'Small 14k gold elephant earrings, with opal ear detail.',
                            'Earrings', 'https://burst.shopifycdn.com/photos/elephant-earrings_925x.jpg'),
                           ('guardian-angel-earrings', 'Guardian Angel Earrings',
                            'Sterling silver guardian angel earrings with diamond gemstones.', 'Earrings',
                            'https://burst.shopifycdn.com/photos/guardian-angel-earrings_925x.jpg'),
                           ('moon-charm-bracelet', 'Moon Charm Bracelet', 'Moon 14k gold chain friendship bracelet.',
                            'Bracelet',
                            'https://burst.shopifycdn.com/photos/womens-hand-moon-bracelet-_925x.jpg'),
                           ('origami-crane-necklace', 'Origami Crane Necklace',
                            'Sterling silver origami crane necklace.', 'Necklace',
                            'https://burst.shopifycdn.com/photos/origami-crane-necklace-gold_925x.jpg'),
                           ('pretty-gold-necklace', 'Pretty Gold Necklace',
                            '14k gold and turquoise necklace. Stunning beaded turquoise on gold and pendant filled double chain design.',
                            'Necklace', 'https://burst.shopifycdn.com/photos/pretty-gold-necklace_925x.jpg'),
                           ('silver-threader-necklace', 'Silver Threader Necklace',
                            'Sterling silver chain thread through circle necklace.',
                            'Necklace', 'https://burst.shopifycdn.com/photos/silver-threader-necklace_925x.jpg'),
                           ('stylish-summer-neclace', 'Stylish Summer Necklace',
                            'Double chained gold boho necklace with turquoise pendant.', 'Necklace',
                            'https://burst.shopifycdn.com/photos/stylish-summer-necklace_925x.jpg')) as p)
insert
into item (catalogue_id, brand_id, name, description, url, type, image)
select floor(random() * 101 + 1)::int,
       floor(random() * 993 + 1)::int,
       d.name,
       d.description,
       d.url || '-' || row_number() over (),
       d.type,
       d.image
from generate_series(1, 10000)
         cross join (select * from data) d;


insert into item_sku (item_id, sku)
select item_id, item_id
from item
where item_id % (select count(*) / 10000 from item) <> 0;


insert into remain (item_id, region_id, price)
select item_id, random() * 85 + 1, random() * 10000 + 1
from item;
